<?php

namespace Database\Seeders;

use App\Models\AcademicYear;
use App\Models\BookName;
use App\Models\Grade;
use App\Models\TeacherGuideSummary;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeacherGuideSummarySeeder extends Seeder
{
    public function run(): void
    {
        $year = AcademicYear::firstOrCreate(
            ['name' => '2025-2026'],
            [
                'is_active' => true,
                'is_current' => true,
                'start_year' => 2025,
                'end_year' => 2026,
                'status' => AcademicYear::STATUS_ACTIVE,
            ]
        );

        // Move any old 2024-2025 summary rows onto the current year.
        $oldYearId = AcademicYear::where('name', '2024-2025')->value('id');
        if ($oldYearId && (int) $oldYearId !== (int) $year->id) {
            TeacherGuideSummary::where('academic_year_id', $oldYearId)
                ->update(['academic_year_id' => $year->id]);
        }

        $rows = [
            [
                'group_no' => 1,
                'group_title' => 'KG
KG
ဆရာလမ်းညွှန်',
                'grade' => 'KG',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'ဘာသာစကားမှီငြမ်းပြုလမ်းညွှန်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1365,
                'total_books' => 1365,
                'distributed_books' => 1350,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 1,
                'group_title' => 'KG
KG
ဆရာလမ်းညွှန်',
                'grade' => 'KG',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'ဆရာလမ်းညွှန်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1365,
                'total_books' => 1365,
                'distributed_books' => 1350,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 1,
                'group_title' => 'KG
KG
ဆရာလမ်းညွှန်',
                'grade' => 'KG',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်ယူမှုပုံစံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1365,
                'total_books' => 1365,
                'distributed_books' => 1350,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 2,
                'group_title' => 'Grade-1
Grade-1
(ဆရာကိုင်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 1,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 685,
                'total_books' => 685,
                'distributed_books' => 675,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 2,
                'group_title' => 'Grade-1
Grade-1
(ဆရာကိုင်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 2,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 2,
                'group_title' => 'Grade-1
Grade-1
(ဆရာကိုင်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 3,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 2,
                'group_title' => 'Grade-1
Grade-1
(ဆရာကိုင်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 4,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'လူမှုရေး',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 685,
                'total_books' => 685,
                'distributed_books' => 675,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 3,
                'group_title' => 'Grade-1
Grade-1
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-1',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 4,
                'group_title' => 'Grade-2
Grade-2
(ဆရာကိုင်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 1,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 685,
                'total_books' => 685,
                'distributed_books' => 675,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 4,
                'group_title' => 'Grade-2
Grade-2
(ဆရာကိုင်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 2,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 4,
                'group_title' => 'Grade-2
Grade-2
(ဆရာကိုင်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 3,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 4,
                'group_title' => 'Grade-2
Grade-2
(ဆရာကိုင်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 4,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'လူမှုရေး',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 685,
                'total_books' => 685,
                'distributed_books' => 675,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 5,
                'group_title' => 'Grade-2
Grade-2
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-2',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 6,
                'group_title' => 'Grade-3
Grade-3
(ဆရာကိုင်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 1,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 685,
                'total_books' => 685,
                'distributed_books' => 675,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 6,
                'group_title' => 'Grade-3
Grade-3
(ဆရာကိုင်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 2,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 6,
                'group_title' => 'Grade-3
Grade-3
(ဆရာကိုင်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 3,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 6,
                'group_title' => 'Grade-3
Grade-3
(ဆရာကိုင်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာကိုင်',
                'sequence_no' => 4,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'လူမှုရေး',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 685,
                'total_books' => 685,
                'distributed_books' => 675,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 7,
                'group_title' => 'Grade-3
Grade-3
(ဆရာလမ်းညွှန်)',
                'grade' => 'Grade-3',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'လူမှုရေး',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'စာရိတ္တနှင့်ပြည့်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 685,
                'total_books' => 685,
                'distributed_books' => 675,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 8,
                'group_title' => 'Grade-4',
                'grade' => 'Grade-4',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'လူမှုရေး',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'စာရိတ္တနှင့်ပြည့်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 685,
                'total_books' => 685,
                'distributed_books' => 675,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 9,
                'group_title' => 'Grade-5',
                'grade' => 'Grade-5',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 1360,
                'total_books' => 1360,
                'distributed_books' => 1350,
                'remaining_books' => 10,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'ပထဝီဝင်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သမိုင်း',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 15,
                'total_books' => 15,
                'distributed_books' => 0,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 10,
                'group_title' => 'Grade-6',
                'grade' => 'Grade-6',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 11,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'ပထဝီဝင်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သမိုင်း',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 15,
                'total_books' => 15,
                'distributed_books' => 0,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 11,
                'group_title' => 'Grade-7',
                'grade' => 'Grade-7',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 11,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'ပထဝီဝင်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သမိုင်း',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 15,
                'total_books' => 15,
                'distributed_books' => 0,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 12,
                'group_title' => 'Grade-8',
                'grade' => 'Grade-8',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 11,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'ပထဝီဝင်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'သမိုင်း',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'သိပ္ပံ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 15,
                'total_books' => 15,
                'distributed_books' => 0,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 13,
                'group_title' => 'Grade-9',
                'grade' => 'Grade-9',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 11,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 327,
                'total_books' => 327,
                'distributed_books' => 312,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 15,
                'total_books' => 15,
                'distributed_books' => 0,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'ဓာတုဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'ရူပဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 11,
                'book_name' => 'ဇီဝဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 12,
                'book_name' => 'လူမှုရေးသိပ္ပံ(ပထဝီ+သမိုင်း+ဘောဂ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 13,
                'book_name' => 'ပထဝီဝင်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 14,
                'book_name' => 'သမိုင်း',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 15,
                'book_name' => 'ဘောဂဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 16,
                'book_name' => 'သိပ္ပံ(ဓာတု+ရူပ+ဇီဝ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 17,
                'book_name' => 'လူမှုရေးသိပ္ပံ(ပထဝီဝင်+သမိုင်း)(ဓာ၊ရူ၊ဘော)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 18,
                'book_name' => 'လူမှုရေးသိပ္ပံ
(ပထဝီဝင်+သမိုင်း)(စိတ်ကြိုက်)',
                'previous_balance' => 0,
                'fiscal_year_quota' => null,
                'total_books' => 0,
                'distributed_books' => 0,
                'remaining_books' => 0,
                'remark' => null,
            ],
            [
                'group_no' => 14,
                'group_title' => 'Grade-10',
                'grade' => 'Grade-10',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 19,
                'book_name' => 'စိတ်ကြိုက်မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => null,
                'total_books' => 0,
                'distributed_books' => 0,
                'remaining_books' => 0,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'စာရိတ္တနှင့်ပြည်သူ့နီတိ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'ဘဝတွက်တာကျွမ်းကျင်စရာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 15,
                'total_books' => 15,
                'distributed_books' => 0,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'ကာယပညာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'အနုပညာ(ပန်းချီ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'အနုပညာ(ဂီတ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'ဓာတုဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'ရူပဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 11,
                'book_name' => 'ဇီဝဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 12,
                'book_name' => 'လူမှုရေးသိပ္ပံ(ပထဝီ+သမိုင်း+ဘောဂ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 13,
                'book_name' => 'ပထဝီဝင်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 14,
                'book_name' => 'သမိုင်း',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 15,
                'book_name' => 'ဘောဂဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 16,
                'book_name' => 'သိပ္ပံ(ဓာတု+ရူပ+ဇီဝ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 17,
                'book_name' => 'လူမှုရေးသိပ္ပံ(ပထဝီဝင်+သမိုင်း)(ဓာ၊ရူ၊ဘော)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 18,
                'book_name' => 'လူမှုရေးသိပ္ပံ
(ပထဝီဝင်+သမိုင်း)(စိတ်ကြိုက်)',
                'previous_balance' => 0,
                'fiscal_year_quota' => null,
                'total_books' => 0,
                'distributed_books' => 0,
                'remaining_books' => 0,
                'remark' => null,
            ],
            [
                'group_no' => 15,
                'group_title' => 'Grade-11',
                'grade' => 'Grade-11',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 19,
                'book_name' => 'စိတ်ကြိုက်မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => null,
                'total_books' => 0,
                'distributed_books' => 0,
                'remaining_books' => 0,
                'remark' => null,
            ],
            [
                'group_no' => 16,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 1,
                'book_name' => 'မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 16,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 2,
                'book_name' => 'အင်္ဂလိပ်စာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 16,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 3,
                'book_name' => 'သင်္ချာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 16,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 4,
                'book_name' => 'ဓာတုဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 16,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 5,
                'book_name' => 'ရူပဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 16,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 6,
                'book_name' => 'ဇီဝဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 17,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 7,
                'book_name' => 'လူမှုရေးသိပ္ပံ(ပထဝီ+သမိုင်း+ဘောဂ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 17,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 8,
                'book_name' => 'ပထဝီဝင်',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 17,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 9,
                'book_name' => 'သမိုင်း',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 17,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 10,
                'book_name' => 'ဘောဂဗေဒ',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 17,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 11,
                'book_name' => 'သိပ္ပံ(ဓာတု+ရူပ+ဇီဝ)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 17,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 12,
                'book_name' => 'လူမှုရေးသိပ္ပံ(ပထဝီဝင်+သမိုင်း)
(ဓာ၊ရူ၊ဘော)',
                'previous_balance' => 0,
                'fiscal_year_quota' => 163,
                'total_books' => 163,
                'distributed_books' => 148,
                'remaining_books' => 15,
                'remark' => null,
            ],
            [
                'group_no' => 17,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 18,
                'book_name' => 'လူမှုရေးသိပ္ပံ
(ပထဝီဝင်+သမိုင်း)(စိတ်ကြိုက်)',
                'previous_balance' => 0,
                'fiscal_year_quota' => null,
                'total_books' => 0,
                'distributed_books' => 0,
                'remaining_books' => 0,
                'remark' => null,
            ],
            [
                'group_no' => 17,
                'group_title' => 'Grade-12',
                'grade' => 'Grade-12',
                'guide_type' => 'ဆရာလမ်းညွှန်',
                'sequence_no' => 19,
                'book_name' => 'စိတ်ကြိုက်မြန်မာစာ',
                'previous_balance' => 0,
                'fiscal_year_quota' => null,
                'total_books' => 0,
                'distributed_books' => 0,
                'remaining_books' => 0,
                'remark' => null,
            ],
        ];

        DB::transaction(function () use ($year, $rows): void {
            foreach ($rows as $row) {
                $grade = Grade::firstOrCreate(
                    ['name' => $row['grade']],
                    ['is_active' => true]
                );

                $bookName = BookName::firstOrCreate(
                    ['name' => $row['book_name']],
                    ['is_active' => true]
                );

                TeacherGuideSummary::updateOrCreate(
                    [
                        'academic_year_id' => $year->id,
                        'group_no' => $row['group_no'],
                        'grade_id' => $grade->id,
                        'book_name_id' => $bookName->id,
                        'guide_type' => $row['guide_type'],
                        'sequence_no' => $row['sequence_no'],
                    ],
                    [
                        'group_title' => $row['group_title'],
                        'previous_balance' => $row['previous_balance'],
                        'fiscal_year_quota' => $row['fiscal_year_quota'],
                        'total_books' => $row['total_books'],
                        'distributed_books' => $row['distributed_books'],
                        'remaining_books' => $row['remaining_books'],
                        'remark' => $row['remark'],
                    ]
                );
            }
        });
    }
}
